---
kind: pipeline
type: docker
name: sqlds

platform:
  os: linux
  arch: amd64

steps:
  - name: "test"
    image: golang:1.16
    commands:
      - go test ./...

---
kind: signature
hmac: 7bdd444f0b237b6b8c5c0217dcb870c9fae03a6f6781dafe159a0df8d0b77b5a

...
